# Generated by Django 5.1.4 on 2025-05-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='carrier_terms',
            field=models.TextField(blank=True, default='6. Driver can be inserted rate deliveries. The undersigned hereby acknowledges and agrees to transport the above referenced shipment, and confirms that Carrier maintains insurance coverage with a minimum of $1,000,000 general liability, $1,000,000 auto liability and $100,000 cargo liability. This Load/Rate Confirmation - Agreement must be signed and returned and faxed to us ****** BEFORE PICKUP. FAX TO NUMBER AT THE TOP OF THE PAGE ******'),
        ),
    ]
