# Generated by Django 5.1.4 on 2025-05-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyinfo_carrier_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='cc_all_emails',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
