# Generated by Django 5.1.4 on 2025-05-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyinfo_cc_all_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcarrier',
            name='address',
        ),
        migrations.AddField(
            model_name='savedcarrier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedcarrier',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='savedcarrier',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedcarrier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='carrier_terms',
            field=models.TextField(blank=True, default='Driver can be inserted rate deliveries. The undersigned hereby acknowledges and agrees to transport the above referenced shipment, and confirms that Carrier maintains insurance coverage with a minimum of $1,000,000 general liability, $1,000,000 auto liability and $100,000 cargo liability. This Load/Rate Confirmation - Agreement must be signed and returned and faxed to us ****** BEFORE PICKUP. FAX TO NUMBER AT THE TOP OF THE PAGE ******'),
        ),
    ]
