# Generated by Django 5.1.4 on 2025-05-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_savedcarrier_address_savedcarrier_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='next_load_number',
            field=models.IntegerField(default=1000),
        ),
    ]
