# Generated by Django 5.1.4 on 2025-05-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_insurancescrapejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcarrier',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcarrier',
            name='coverage_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcarrier',
            name='coverage_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcarrier',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcarrier',
            name='insurance_carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedcarrier',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='savedcarrier',
            name='policy_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='savedcarrier',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
